pipeline {
    agent {
        docker {
            image 'maven:3-aplpine'
            args '-v /root/.m2:/root/.m2/'
        }
    }
    stage {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}
